'use server';

import { BlogFormData } from '@/types/blog.types';

export async function createBlog(data: BlogFormData) {
  try {
    // Generate slug from title
    const slug = data.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');

    // Calculate read time (rough estimate: 200 words per minute)
    const wordCount = data.content.split(/\s+/).length;
    const readTime = Math.ceil(wordCount / 200);

    const blogPost = {
      ...data,
      id: Date.now().toString(), // In real app, this would be generated by database
      slug,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      readTime
    };

    // TODO: Save to database
    console.log('Creating blog post:', blogPost);

    return {
      success: true,
      data: blogPost,
      message: 'Blog post created successfully!'
    };
  } catch (error) {
    console.error('Error creating blog:', error);
    return {
      success: false,
      error: 'Failed to create blog post',
      message: undefined
    };
  }
}

export async function saveDraft(data: BlogFormData) {
  try {
    const draftData = {
      ...data,
      status: 'draft' as const,
      updatedAt: new Date().toISOString()
    };

    // TODO: Save draft to database
    console.log('Saving draft:', draftData);

    return {
      success: true,
      message: 'Draft saved successfully!'
    };
  } catch (error) {
    console.error('Error saving draft:', error);
    return {
      success: false,
      error: 'Failed to save draft',
      message: undefined
    };
  }
}
